// Generated by gencpp from file farm_node/farm_nodeResponse.msg
// DO NOT EDIT!


#ifndef FARM_NODE_MESSAGE_FARM_NODERESPONSE_H
#define FARM_NODE_MESSAGE_FARM_NODERESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace farm_node
{
template <class ContainerAllocator>
struct farm_nodeResponse_
{
  typedef farm_nodeResponse_<ContainerAllocator> Type;

  farm_nodeResponse_()
    : op(false)  {
    }
  farm_nodeResponse_(const ContainerAllocator& _alloc)
    : op(false)  {
  (void)_alloc;
    }



   typedef uint8_t _op_type;
  _op_type op;





  typedef boost::shared_ptr< ::farm_node::farm_nodeResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::farm_node::farm_nodeResponse_<ContainerAllocator> const> ConstPtr;

}; // struct farm_nodeResponse_

typedef ::farm_node::farm_nodeResponse_<std::allocator<void> > farm_nodeResponse;

typedef boost::shared_ptr< ::farm_node::farm_nodeResponse > farm_nodeResponsePtr;
typedef boost::shared_ptr< ::farm_node::farm_nodeResponse const> farm_nodeResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::farm_node::farm_nodeResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::farm_node::farm_nodeResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::farm_node::farm_nodeResponse_<ContainerAllocator1> & lhs, const ::farm_node::farm_nodeResponse_<ContainerAllocator2> & rhs)
{
  return lhs.op == rhs.op;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::farm_node::farm_nodeResponse_<ContainerAllocator1> & lhs, const ::farm_node::farm_nodeResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace farm_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::farm_node::farm_nodeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::farm_node::farm_nodeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::farm_node::farm_nodeResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::farm_node::farm_nodeResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::farm_node::farm_nodeResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::farm_node::farm_nodeResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::farm_node::farm_nodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f9d9565f906a018a008bc4ee123f9661";
  }

  static const char* value(const ::farm_node::farm_nodeResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf9d9565f906a018aULL;
  static const uint64_t static_value2 = 0x008bc4ee123f9661ULL;
};

template<class ContainerAllocator>
struct DataType< ::farm_node::farm_nodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "farm_node/farm_nodeResponse";
  }

  static const char* value(const ::farm_node::farm_nodeResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::farm_node::farm_nodeResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool op\n"
"\n"
;
  }

  static const char* value(const ::farm_node::farm_nodeResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::farm_node::farm_nodeResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.op);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct farm_nodeResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::farm_node::farm_nodeResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::farm_node::farm_nodeResponse_<ContainerAllocator>& v)
  {
    s << indent << "op: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.op);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FARM_NODE_MESSAGE_FARM_NODERESPONSE_H
