// Generated by gencpp from file farm_node/farm_nodeRequest.msg
// DO NOT EDIT!


#ifndef FARM_NODE_MESSAGE_FARM_NODEREQUEST_H
#define FARM_NODE_MESSAGE_FARM_NODEREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace farm_node
{
template <class ContainerAllocator>
struct farm_nodeRequest_
{
  typedef farm_nodeRequest_<ContainerAllocator> Type;

  farm_nodeRequest_()
    : ip(false)  {
    }
  farm_nodeRequest_(const ContainerAllocator& _alloc)
    : ip(false)  {
  (void)_alloc;
    }



   typedef uint8_t _ip_type;
  _ip_type ip;





  typedef boost::shared_ptr< ::farm_node::farm_nodeRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::farm_node::farm_nodeRequest_<ContainerAllocator> const> ConstPtr;

}; // struct farm_nodeRequest_

typedef ::farm_node::farm_nodeRequest_<std::allocator<void> > farm_nodeRequest;

typedef boost::shared_ptr< ::farm_node::farm_nodeRequest > farm_nodeRequestPtr;
typedef boost::shared_ptr< ::farm_node::farm_nodeRequest const> farm_nodeRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::farm_node::farm_nodeRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::farm_node::farm_nodeRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::farm_node::farm_nodeRequest_<ContainerAllocator1> & lhs, const ::farm_node::farm_nodeRequest_<ContainerAllocator2> & rhs)
{
  return lhs.ip == rhs.ip;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::farm_node::farm_nodeRequest_<ContainerAllocator1> & lhs, const ::farm_node::farm_nodeRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace farm_node

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::farm_node::farm_nodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::farm_node::farm_nodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::farm_node::farm_nodeRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::farm_node::farm_nodeRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::farm_node::farm_nodeRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::farm_node::farm_nodeRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::farm_node::farm_nodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "32948355ebd3194c1579c20a89cdd074";
  }

  static const char* value(const ::farm_node::farm_nodeRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x32948355ebd3194cULL;
  static const uint64_t static_value2 = 0x1579c20a89cdd074ULL;
};

template<class ContainerAllocator>
struct DataType< ::farm_node::farm_nodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "farm_node/farm_nodeRequest";
  }

  static const char* value(const ::farm_node::farm_nodeRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::farm_node::farm_nodeRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool ip\n"
;
  }

  static const char* value(const ::farm_node::farm_nodeRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::farm_node::farm_nodeRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ip);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct farm_nodeRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::farm_node::farm_nodeRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::farm_node::farm_nodeRequest_<ContainerAllocator>& v)
  {
    s << indent << "ip: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ip);
  }
};

} // namespace message_operations
} // namespace ros

#endif // FARM_NODE_MESSAGE_FARM_NODEREQUEST_H
