// Generated by gencpp from file farm_node/farm_node.msg
// DO NOT EDIT!


#ifndef FARM_NODE_MESSAGE_FARM_NODE_H
#define FARM_NODE_MESSAGE_FARM_NODE_H

#include <ros/service_traits.h>


#include <farm_node/farm_nodeRequest.h>
#include <farm_node/farm_nodeResponse.h>


namespace farm_node
{

struct farm_node
{

typedef farm_nodeRequest Request;
typedef farm_nodeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct farm_node
} // namespace farm_node


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::farm_node::farm_node > {
  static const char* value()
  {
    return "84e7488d3da383232f3536b550a9c06e";
  }

  static const char* value(const ::farm_node::farm_node&) { return value(); }
};

template<>
struct DataType< ::farm_node::farm_node > {
  static const char* value()
  {
    return "farm_node/farm_node";
  }

  static const char* value(const ::farm_node::farm_node&) { return value(); }
};


// service_traits::MD5Sum< ::farm_node::farm_nodeRequest> should match
// service_traits::MD5Sum< ::farm_node::farm_node >
template<>
struct MD5Sum< ::farm_node::farm_nodeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::farm_node::farm_node >::value();
  }
  static const char* value(const ::farm_node::farm_nodeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::farm_node::farm_nodeRequest> should match
// service_traits::DataType< ::farm_node::farm_node >
template<>
struct DataType< ::farm_node::farm_nodeRequest>
{
  static const char* value()
  {
    return DataType< ::farm_node::farm_node >::value();
  }
  static const char* value(const ::farm_node::farm_nodeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::farm_node::farm_nodeResponse> should match
// service_traits::MD5Sum< ::farm_node::farm_node >
template<>
struct MD5Sum< ::farm_node::farm_nodeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::farm_node::farm_node >::value();
  }
  static const char* value(const ::farm_node::farm_nodeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::farm_node::farm_nodeResponse> should match
// service_traits::DataType< ::farm_node::farm_node >
template<>
struct DataType< ::farm_node::farm_nodeResponse>
{
  static const char* value()
  {
    return DataType< ::farm_node::farm_node >::value();
  }
  static const char* value(const ::farm_node::farm_nodeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // FARM_NODE_MESSAGE_FARM_NODE_H
