# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from copernicus_msgs/BMS.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class BMS(genpy.Message):
  _md5sum = "e56275de8110c71d2252135812351394"
  _type = "copernicus_msgs/BMS"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """uint16 SOC
uint16 Voltage
int16 Current"""
  __slots__ = ['SOC','Voltage','Current']
  _slot_types = ['uint16','uint16','int16']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       SOC,Voltage,Current

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(BMS, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.SOC is None:
        self.SOC = 0
      if self.Voltage is None:
        self.Voltage = 0
      if self.Current is None:
        self.Current = 0
    else:
      self.SOC = 0
      self.Voltage = 0
      self.Current = 0

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_2Hh().pack(_x.SOC, _x.Voltage, _x.Current))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.SOC, _x.Voltage, _x.Current,) = _get_struct_2Hh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_2Hh().pack(_x.SOC, _x.Voltage, _x.Current))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      end = 0
      _x = self
      start = end
      end += 6
      (_x.SOC, _x.Voltage, _x.Current,) = _get_struct_2Hh().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_2Hh = None
def _get_struct_2Hh():
    global _struct_2Hh
    if _struct_2Hh is None:
        _struct_2Hh = struct.Struct("<2Hh")
    return _struct_2Hh
