// Generated by gencpp from file diff_drive_controller/AccelerationRequest.msg
// DO NOT EDIT!


#ifndef DIFF_DRIVE_CONTROLLER_MESSAGE_ACCELERATIONREQUEST_H
#define DIFF_DRIVE_CONTROLLER_MESSAGE_ACCELERATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace diff_drive_controller
{
template <class ContainerAllocator>
struct AccelerationRequest_
{
  typedef AccelerationRequest_<ContainerAllocator> Type;

  AccelerationRequest_()
    : acceleration(0.0)  {
    }
  AccelerationRequest_(const ContainerAllocator& _alloc)
    : acceleration(0.0)  {
  (void)_alloc;
    }



   typedef double _acceleration_type;
  _acceleration_type acceleration;





  typedef boost::shared_ptr< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AccelerationRequest_

typedef ::diff_drive_controller::AccelerationRequest_<std::allocator<void> > AccelerationRequest;

typedef boost::shared_ptr< ::diff_drive_controller::AccelerationRequest > AccelerationRequestPtr;
typedef boost::shared_ptr< ::diff_drive_controller::AccelerationRequest const> AccelerationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diff_drive_controller::AccelerationRequest_<ContainerAllocator1> & lhs, const ::diff_drive_controller::AccelerationRequest_<ContainerAllocator2> & rhs)
{
  return lhs.acceleration == rhs.acceleration;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diff_drive_controller::AccelerationRequest_<ContainerAllocator1> & lhs, const ::diff_drive_controller::AccelerationRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diff_drive_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7116d79853cec8276f2ea65056d18b78";
  }

  static const char* value(const ::diff_drive_controller::AccelerationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7116d79853cec827ULL;
  static const uint64_t static_value2 = 0x6f2ea65056d18b78ULL;
};

template<class ContainerAllocator>
struct DataType< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diff_drive_controller/AccelerationRequest";
  }

  static const char* value(const ::diff_drive_controller::AccelerationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 acceleration\n"
;
  }

  static const char* value(const ::diff_drive_controller::AccelerationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.acceleration);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AccelerationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diff_drive_controller::AccelerationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diff_drive_controller::AccelerationRequest_<ContainerAllocator>& v)
  {
    s << indent << "acceleration: ";
    Printer<double>::stream(s, indent + "  ", v.acceleration);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIFF_DRIVE_CONTROLLER_MESSAGE_ACCELERATIONREQUEST_H
