// Generated by gencpp from file diff_drive_controller/AccelerationResponse.msg
// DO NOT EDIT!


#ifndef DIFF_DRIVE_CONTROLLER_MESSAGE_ACCELERATIONRESPONSE_H
#define DIFF_DRIVE_CONTROLLER_MESSAGE_ACCELERATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace diff_drive_controller
{
template <class ContainerAllocator>
struct AccelerationResponse_
{
  typedef AccelerationResponse_<ContainerAllocator> Type;

  AccelerationResponse_()
    : success(false)  {
    }
  AccelerationResponse_(const ContainerAllocator& _alloc)
    : success(false)  {
  (void)_alloc;
    }



   typedef uint8_t _success_type;
  _success_type success;





  typedef boost::shared_ptr< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AccelerationResponse_

typedef ::diff_drive_controller::AccelerationResponse_<std::allocator<void> > AccelerationResponse;

typedef boost::shared_ptr< ::diff_drive_controller::AccelerationResponse > AccelerationResponsePtr;
typedef boost::shared_ptr< ::diff_drive_controller::AccelerationResponse const> AccelerationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diff_drive_controller::AccelerationResponse_<ContainerAllocator1> & lhs, const ::diff_drive_controller::AccelerationResponse_<ContainerAllocator2> & rhs)
{
  return lhs.success == rhs.success;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diff_drive_controller::AccelerationResponse_<ContainerAllocator1> & lhs, const ::diff_drive_controller::AccelerationResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diff_drive_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "358e233cde0c8a8bcfea4ce193f8fc15";
  }

  static const char* value(const ::diff_drive_controller::AccelerationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x358e233cde0c8a8bULL;
  static const uint64_t static_value2 = 0xcfea4ce193f8fc15ULL;
};

template<class ContainerAllocator>
struct DataType< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diff_drive_controller/AccelerationResponse";
  }

  static const char* value(const ::diff_drive_controller::AccelerationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool success\n"
;
  }

  static const char* value(const ::diff_drive_controller::AccelerationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.success);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AccelerationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diff_drive_controller::AccelerationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diff_drive_controller::AccelerationResponse_<ContainerAllocator>& v)
  {
    s << indent << "success: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.success);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIFF_DRIVE_CONTROLLER_MESSAGE_ACCELERATIONRESPONSE_H
