// Generated by gencpp from file diff_drive_controller/Acceleration.msg
// DO NOT EDIT!


#ifndef DIFF_DRIVE_CONTROLLER_MESSAGE_ACCELERATION_H
#define DIFF_DRIVE_CONTROLLER_MESSAGE_ACCELERATION_H

#include <ros/service_traits.h>


#include <diff_drive_controller/AccelerationRequest.h>
#include <diff_drive_controller/AccelerationResponse.h>


namespace diff_drive_controller
{

struct Acceleration
{

typedef AccelerationRequest Request;
typedef AccelerationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Acceleration
} // namespace diff_drive_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::diff_drive_controller::Acceleration > {
  static const char* value()
  {
    return "fad4e19098f080ace41a4a41c6498a2e";
  }

  static const char* value(const ::diff_drive_controller::Acceleration&) { return value(); }
};

template<>
struct DataType< ::diff_drive_controller::Acceleration > {
  static const char* value()
  {
    return "diff_drive_controller/Acceleration";
  }

  static const char* value(const ::diff_drive_controller::Acceleration&) { return value(); }
};


// service_traits::MD5Sum< ::diff_drive_controller::AccelerationRequest> should match
// service_traits::MD5Sum< ::diff_drive_controller::Acceleration >
template<>
struct MD5Sum< ::diff_drive_controller::AccelerationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::diff_drive_controller::Acceleration >::value();
  }
  static const char* value(const ::diff_drive_controller::AccelerationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::diff_drive_controller::AccelerationRequest> should match
// service_traits::DataType< ::diff_drive_controller::Acceleration >
template<>
struct DataType< ::diff_drive_controller::AccelerationRequest>
{
  static const char* value()
  {
    return DataType< ::diff_drive_controller::Acceleration >::value();
  }
  static const char* value(const ::diff_drive_controller::AccelerationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::diff_drive_controller::AccelerationResponse> should match
// service_traits::MD5Sum< ::diff_drive_controller::Acceleration >
template<>
struct MD5Sum< ::diff_drive_controller::AccelerationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::diff_drive_controller::Acceleration >::value();
  }
  static const char* value(const ::diff_drive_controller::AccelerationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::diff_drive_controller::AccelerationResponse> should match
// service_traits::DataType< ::diff_drive_controller::Acceleration >
template<>
struct DataType< ::diff_drive_controller::AccelerationResponse>
{
  static const char* value()
  {
    return DataType< ::diff_drive_controller::Acceleration >::value();
  }
  static const char* value(const ::diff_drive_controller::AccelerationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DIFF_DRIVE_CONTROLLER_MESSAGE_ACCELERATION_H
