// Generated by gencpp from file diff_drive_controller/Velocity.msg
// DO NOT EDIT!


#ifndef DIFF_DRIVE_CONTROLLER_MESSAGE_VELOCITY_H
#define DIFF_DRIVE_CONTROLLER_MESSAGE_VELOCITY_H

#include <ros/service_traits.h>


#include <diff_drive_controller/VelocityRequest.h>
#include <diff_drive_controller/VelocityResponse.h>


namespace diff_drive_controller
{

struct Velocity
{

typedef VelocityRequest Request;
typedef VelocityResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Velocity
} // namespace diff_drive_controller


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::diff_drive_controller::Velocity > {
  static const char* value()
  {
    return "389d67e2fda96fe6bf741fde2129c825";
  }

  static const char* value(const ::diff_drive_controller::Velocity&) { return value(); }
};

template<>
struct DataType< ::diff_drive_controller::Velocity > {
  static const char* value()
  {
    return "diff_drive_controller/Velocity";
  }

  static const char* value(const ::diff_drive_controller::Velocity&) { return value(); }
};


// service_traits::MD5Sum< ::diff_drive_controller::VelocityRequest> should match
// service_traits::MD5Sum< ::diff_drive_controller::Velocity >
template<>
struct MD5Sum< ::diff_drive_controller::VelocityRequest>
{
  static const char* value()
  {
    return MD5Sum< ::diff_drive_controller::Velocity >::value();
  }
  static const char* value(const ::diff_drive_controller::VelocityRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::diff_drive_controller::VelocityRequest> should match
// service_traits::DataType< ::diff_drive_controller::Velocity >
template<>
struct DataType< ::diff_drive_controller::VelocityRequest>
{
  static const char* value()
  {
    return DataType< ::diff_drive_controller::Velocity >::value();
  }
  static const char* value(const ::diff_drive_controller::VelocityRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::diff_drive_controller::VelocityResponse> should match
// service_traits::MD5Sum< ::diff_drive_controller::Velocity >
template<>
struct MD5Sum< ::diff_drive_controller::VelocityResponse>
{
  static const char* value()
  {
    return MD5Sum< ::diff_drive_controller::Velocity >::value();
  }
  static const char* value(const ::diff_drive_controller::VelocityResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::diff_drive_controller::VelocityResponse> should match
// service_traits::DataType< ::diff_drive_controller::Velocity >
template<>
struct DataType< ::diff_drive_controller::VelocityResponse>
{
  static const char* value()
  {
    return DataType< ::diff_drive_controller::Velocity >::value();
  }
  static const char* value(const ::diff_drive_controller::VelocityResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // DIFF_DRIVE_CONTROLLER_MESSAGE_VELOCITY_H
