// Generated by gencpp from file diff_drive_controller/VelocityRequest.msg
// DO NOT EDIT!


#ifndef DIFF_DRIVE_CONTROLLER_MESSAGE_VELOCITYREQUEST_H
#define DIFF_DRIVE_CONTROLLER_MESSAGE_VELOCITYREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace diff_drive_controller
{
template <class ContainerAllocator>
struct VelocityRequest_
{
  typedef VelocityRequest_<ContainerAllocator> Type;

  VelocityRequest_()
    : velocity(0.0)  {
    }
  VelocityRequest_(const ContainerAllocator& _alloc)
    : velocity(0.0)  {
  (void)_alloc;
    }



   typedef double _velocity_type;
  _velocity_type velocity;





  typedef boost::shared_ptr< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> const> ConstPtr;

}; // struct VelocityRequest_

typedef ::diff_drive_controller::VelocityRequest_<std::allocator<void> > VelocityRequest;

typedef boost::shared_ptr< ::diff_drive_controller::VelocityRequest > VelocityRequestPtr;
typedef boost::shared_ptr< ::diff_drive_controller::VelocityRequest const> VelocityRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::diff_drive_controller::VelocityRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::diff_drive_controller::VelocityRequest_<ContainerAllocator1> & lhs, const ::diff_drive_controller::VelocityRequest_<ContainerAllocator2> & rhs)
{
  return lhs.velocity == rhs.velocity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::diff_drive_controller::VelocityRequest_<ContainerAllocator1> & lhs, const ::diff_drive_controller::VelocityRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace diff_drive_controller

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6d3b2ef8452c2fe21adb709618d2518f";
  }

  static const char* value(const ::diff_drive_controller::VelocityRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6d3b2ef8452c2fe2ULL;
  static const uint64_t static_value2 = 0x1adb709618d2518fULL;
};

template<class ContainerAllocator>
struct DataType< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "diff_drive_controller/VelocityRequest";
  }

  static const char* value(const ::diff_drive_controller::VelocityRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 velocity\n"
;
  }

  static const char* value(const ::diff_drive_controller::VelocityRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.velocity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct VelocityRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::diff_drive_controller::VelocityRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::diff_drive_controller::VelocityRequest_<ContainerAllocator>& v)
  {
    s << indent << "velocity: ";
    Printer<double>::stream(s, indent + "  ", v.velocity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // DIFF_DRIVE_CONTROLLER_MESSAGE_VELOCITYREQUEST_H
