// Generated by gencpp from file copernicus_msgs/BMS.msg
// DO NOT EDIT!


#ifndef COPERNICUS_MSGS_MESSAGE_BMS_H
#define COPERNICUS_MSGS_MESSAGE_BMS_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace copernicus_msgs
{
template <class ContainerAllocator>
struct BMS_
{
  typedef BMS_<ContainerAllocator> Type;

  BMS_()
    : SOC(0)
    , Voltage(0)
    , Current(0)  {
    }
  BMS_(const ContainerAllocator& _alloc)
    : SOC(0)
    , Voltage(0)
    , Current(0)  {
  (void)_alloc;
    }



   typedef uint16_t _SOC_type;
  _SOC_type SOC;

   typedef uint16_t _Voltage_type;
  _Voltage_type Voltage;

   typedef int16_t _Current_type;
  _Current_type Current;





  typedef boost::shared_ptr< ::copernicus_msgs::BMS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::copernicus_msgs::BMS_<ContainerAllocator> const> ConstPtr;

}; // struct BMS_

typedef ::copernicus_msgs::BMS_<std::allocator<void> > BMS;

typedef boost::shared_ptr< ::copernicus_msgs::BMS > BMSPtr;
typedef boost::shared_ptr< ::copernicus_msgs::BMS const> BMSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::copernicus_msgs::BMS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::copernicus_msgs::BMS_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::copernicus_msgs::BMS_<ContainerAllocator1> & lhs, const ::copernicus_msgs::BMS_<ContainerAllocator2> & rhs)
{
  return lhs.SOC == rhs.SOC &&
    lhs.Voltage == rhs.Voltage &&
    lhs.Current == rhs.Current;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::copernicus_msgs::BMS_<ContainerAllocator1> & lhs, const ::copernicus_msgs::BMS_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace copernicus_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::copernicus_msgs::BMS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::copernicus_msgs::BMS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::copernicus_msgs::BMS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::copernicus_msgs::BMS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::copernicus_msgs::BMS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::copernicus_msgs::BMS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::copernicus_msgs::BMS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e56275de8110c71d2252135812351394";
  }

  static const char* value(const ::copernicus_msgs::BMS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe56275de8110c71dULL;
  static const uint64_t static_value2 = 0x2252135812351394ULL;
};

template<class ContainerAllocator>
struct DataType< ::copernicus_msgs::BMS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "copernicus_msgs/BMS";
  }

  static const char* value(const ::copernicus_msgs::BMS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::copernicus_msgs::BMS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16 SOC\n"
"uint16 Voltage\n"
"int16 Current\n"
;
  }

  static const char* value(const ::copernicus_msgs::BMS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::copernicus_msgs::BMS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SOC);
      stream.next(m.Voltage);
      stream.next(m.Current);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BMS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::copernicus_msgs::BMS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::copernicus_msgs::BMS_<ContainerAllocator>& v)
  {
    s << indent << "SOC: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.SOC);
    s << indent << "Voltage: ";
    Printer<uint16_t>::stream(s, indent + "  ", v.Voltage);
    s << indent << "Current: ";
    Printer<int16_t>::stream(s, indent + "  ", v.Current);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COPERNICUS_MSGS_MESSAGE_BMS_H
