// Generated by gencpp from file copernicus_msgs/SonarSensor.msg
// DO NOT EDIT!


#ifndef COPERNICUS_MSGS_MESSAGE_SONARSENSOR_H
#define COPERNICUS_MSGS_MESSAGE_SONARSENSOR_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace copernicus_msgs
{
template <class ContainerAllocator>
struct SonarSensor_
{
  typedef SonarSensor_<ContainerAllocator> Type;

  SonarSensor_()
    : SONAR()  {
      SONAR.assign(0);
  }
  SonarSensor_(const ContainerAllocator& _alloc)
    : SONAR()  {
  (void)_alloc;
      SONAR.assign(0);
  }



   typedef boost::array<uint16_t, 6>  _SONAR_type;
  _SONAR_type SONAR;





  typedef boost::shared_ptr< ::copernicus_msgs::SonarSensor_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::copernicus_msgs::SonarSensor_<ContainerAllocator> const> ConstPtr;

}; // struct SonarSensor_

typedef ::copernicus_msgs::SonarSensor_<std::allocator<void> > SonarSensor;

typedef boost::shared_ptr< ::copernicus_msgs::SonarSensor > SonarSensorPtr;
typedef boost::shared_ptr< ::copernicus_msgs::SonarSensor const> SonarSensorConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::copernicus_msgs::SonarSensor_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::copernicus_msgs::SonarSensor_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::copernicus_msgs::SonarSensor_<ContainerAllocator1> & lhs, const ::copernicus_msgs::SonarSensor_<ContainerAllocator2> & rhs)
{
  return lhs.SONAR == rhs.SONAR;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::copernicus_msgs::SonarSensor_<ContainerAllocator1> & lhs, const ::copernicus_msgs::SonarSensor_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace copernicus_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::copernicus_msgs::SonarSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::copernicus_msgs::SonarSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::copernicus_msgs::SonarSensor_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::copernicus_msgs::SonarSensor_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::copernicus_msgs::SonarSensor_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::copernicus_msgs::SonarSensor_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::copernicus_msgs::SonarSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7d763eec883429d5f3e9ebc343ccfa65";
  }

  static const char* value(const ::copernicus_msgs::SonarSensor_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7d763eec883429d5ULL;
  static const uint64_t static_value2 = 0xf3e9ebc343ccfa65ULL;
};

template<class ContainerAllocator>
struct DataType< ::copernicus_msgs::SonarSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "copernicus_msgs/SonarSensor";
  }

  static const char* value(const ::copernicus_msgs::SonarSensor_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::copernicus_msgs::SonarSensor_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint16[6]    SONAR\n"
;
  }

  static const char* value(const ::copernicus_msgs::SonarSensor_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::copernicus_msgs::SonarSensor_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.SONAR);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SonarSensor_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::copernicus_msgs::SonarSensor_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::copernicus_msgs::SonarSensor_<ContainerAllocator>& v)
  {
    s << indent << "SONAR[]" << std::endl;
    for (size_t i = 0; i < v.SONAR.size(); ++i)
    {
      s << indent << "  SONAR[" << i << "]: ";
      Printer<uint16_t>::stream(s, indent + "  ", v.SONAR[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // COPERNICUS_MSGS_MESSAGE_SONARSENSOR_H
